project:
  type: default
  output-dir: build
  resources:
    - resources/brainrender.html

bibliography: references.bib

execute:
  enabled: true

format:
  revealjs:
    theme: [bg-light.scss]
    logo: img/BG_logo.png
    footer: "[https://brainglobe.info/slides-allen-brainglobe-atlasapi](https://brainglobe.info/slides-allen-brainglobe-atlasapi) | 2026-09-21"
    slide-number: c
    menu:
      numbers: true
      useTextContentForMissingTitles: false 
      hideMissingTitles: true
    chalkboard: true
    scrollable: false
    preview-links: false
    view-distance: 10
    mobile-view-distance: 10
    auto-animate: true
    auto-animate-easing: ease-in
    auto-animate-duration: 0.5
    auto-play-media: true
    code-overflow: wrap
    highlight-style: atom-one
    from: markdown+emoji   # enable emoji support
    mermaid:
      theme: neutral
      fontFamily: arial
      curve: linear
